Repository TeamMajorLink/majorLink_server, pull requests merged in 2024-08, with the labels that each got.

#17 ✨ [FEAT] 소셜 로그인
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/majorLink.main.iml
  .idea/modules/majorLink.test.iml
  .idea/uiDesigner.xml
  logs/app.log/spring.log
  majorLink/.gitignore
  majorLink/build.gradle
  majorLink/src/main/java/com/example/majorLink/MajorLinkApplication.java
  majorLink/src/main/java/com/example/majorLink/controller/UserController.java
  majorLink/src/main/java/com/example/majorLink/domain/Notification.java
  majorLink/src/main/java/com/example/majorLink/domain/Social.java
  majorLink/src/main/java/com/example/majorLink/domain/User.java
  majorLink/src/main/java/com/example/majorLink/domain/enums/SocialStatus.java
  majorLink/src/main/java/com/example/majorLink/domain/enums/UserStatus.java
  majorLink/src/main/java/com/example/majorLink/dto/request/SignInRequest.java
  majorLink/src/main/java/com/example/majorLink/dto/request/SignUpRequest.java
  majorLink/src/main/java/com/example/majorLink/dto/response/FirstLoginResponse.java
  majorLink/src/main/java/com/example/majorLink/global/auth/AuthController.java
  majorLink/src/main/java/com/example/majorLink/global/auth/AuthTokens.java
  majorLink/src/main/java/com/example/majorLink/global/auth/AuthUser.java
  majorLink/src/main/java/com/example/majorLink/global/auth/Tokens.java
  majorLink/src/main/java/com/example/majorLink/global/auth/service/RedisService.java
  majorLink/src/main/java/com/example/majorLink/global/auth/service/SocialService.java
  majorLink/src/main/java/com/example/majorLink/global/auth/service/UserDetailsService.java
  majorLink/src/main/java/com/example/majorLink/global/config/ClientConfig.java
  majorLink/src/main/java/com/example/majorLink/global/config/SecurityConfig.java
  majorLink/src/main/java/com/example/majorLink/global/jwt/JwtAuthenticationFilter.java
  majorLink/src/main/java/com/example/majorLink/global/jwt/JwtConfig.java
  majorLink/src/main/java/com/example/majorLink/global/jwt/JwtService.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/CustomOAuth2User.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuth2AuthenticationFailureHandler.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuth2AuthenticationSuccessHandler.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuthAttributes.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuthLoginService.java
  majorLink/src/main/java/com/example/majorLink/repository/SocialRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/UserRepository.java
  majorLink/src/main/java/com/example/majorLink/service/UserService.java
  majorLink/src/main/java/com/example/majorLink/service/UserServiceImpl.java
  majorLink/src/main/resources/application.yml
Labels: ✨ feature

#15 Feat#12 stomp 실시간 채팅 기능 구현(테스트 이전 상태)
  majorLink/build.gradle
  majorLink/src/main/java/com/example/majorLink/controller/ChatController.java
  majorLink/src/main/java/com/example/majorLink/converter/ChatRoomConverter.java
  majorLink/src/main/java/com/example/majorLink/domain/ChatMessage.java
  majorLink/src/main/java/com/example/majorLink/domain/ChatRoom.java
  majorLink/src/main/java/com/example/majorLink/dto/ChatRoomRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/ChatRoomResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/global/config/WebConfig.java
  majorLink/src/main/java/com/example/majorLink/global/config/WebSocketConfig.java
  majorLink/src/main/java/com/example/majorLink/repository/ChatMessageRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/ChatRoomRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/UserChatRepository.java
  majorLink/src/main/java/com/example/majorLink/service/ChatService.java
  majorLink/src/main/java/com/example/majorLink/service/ChatServiceImpl.java
Labels: ✨ feature

#19 ✨ [Feat] 리뷰 기능 구현
  majorLink/src/main/java/com/example/majorLink/controller/ReviewController.java
  majorLink/src/main/java/com/example/majorLink/domain/Category.java
  majorLink/src/main/java/com/example/majorLink/domain/Lecture.java
  majorLink/src/main/java/com/example/majorLink/domain/Review.java
  majorLink/src/main/java/com/example/majorLink/domain/Tag.java
  majorLink/src/main/java/com/example/majorLink/dto/request/ReviewRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/ReviewResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/LectureRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/ReviewRepository.java
  majorLink/src/main/java/com/example/majorLink/service/ReviewService/ReviewService.java
  majorLink/src/main/java/com/example/majorLink/service/ReviewService/ReviewServiceImpl.java
Labels: ✨ feature

#35 도커 확인용
  majorLink/src/main/resources/application.yml
Labels: 🐛 bug

#37 헬스 체커 api
  majorLink/src/main/java/com/example/majorLink/controller/HealtyCheckController.java
Labels: ✨ feature

#28 ✨ [FEAT] 결제 요청 및 주문 데이터 저장
  majorLink/build.gradle
  majorLink/src/main/java/com/example/majorLink/controller/PaymentController.java
  majorLink/src/main/java/com/example/majorLink/domain/Payment.java
  majorLink/src/main/java/com/example/majorLink/domain/ProductOrder.java
  majorLink/src/main/java/com/example/majorLink/domain/enums/PaymentStatus.java
  majorLink/src/main/java/com/example/majorLink/domain/enums/Product.java
  majorLink/src/main/java/com/example/majorLink/dto/request/PaymentRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/request/ProductOrderRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/PaymentResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/ProductOrderResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/PaymentRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/ProductOrderRepository.java
  majorLink/src/main/java/com/example/majorLink/service/PaymentService/PaymentService.java
  majorLink/src/main/java/com/example/majorLink/service/PaymentService/PaymentServiceImpl.java
  majorLink/src/main/resources/application.yml
Labels: ✨ feature

#39 Update cicd.yml (레디스 옵션 추가)
  .github/workflows/cicd.yml
Labels: ✨ feature

#41 ✨ [FEAT] 강의 기능 구현
  majorLink/src/main/java/com/example/majorLink/controller/LectureController.java
  majorLink/src/main/java/com/example/majorLink/controller/ReviewController.java
  majorLink/src/main/java/com/example/majorLink/domain/Category.java
  majorLink/src/main/java/com/example/majorLink/domain/Lecture.java
  majorLink/src/main/java/com/example/majorLink/domain/Tag.java
  majorLink/src/main/java/com/example/majorLink/domain/enums/LectureStatus.java
  majorLink/src/main/java/com/example/majorLink/domain/mapping/TuteeLecture.java
  majorLink/src/main/java/com/example/majorLink/domain/mapping/TutorLecture.java
  majorLink/src/main/java/com/example/majorLink/dto/request/LectureRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/LectureResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/LectureRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/LikedRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/TagRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/TuteeLectureRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/TutorLectureRepository.java
  majorLink/src/main/java/com/example/majorLink/service/LectureService.java
  majorLink/src/main/java/com/example/majorLink/service/LectureServiceImpl.java
  majorLink/src/main/java/com/example/majorLink/service/ReviewService/ReviewService.java
  majorLink/src/main/java/com/example/majorLink/service/ReviewService/ReviewServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#45 ✨[FEAT] 로그인 API 연동을 위한 providerId, accessToken 반환
  .idea/compiler.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  majorLink/src/main/java/com/example/majorLink/global/auth/AuthController.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuth2AuthenticationSuccessHandler.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuthAttributes.java
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuthLoginService.java
  majorLink/src/main/resources/application.yml
Labels: ✨ feature

#46 🚑 [HOTFIX] CORS 에러 해결을 위한 WebConfig 수정
  .idea/jarRepositories.xml
  majorLink/src/main/java/com/example/majorLink/global/config/WebConfig.java
Labels: 🚑 Hotfix

#47 ✨ [FEAT] 클래스 목록 조회 및 검색 기능
  majorLink/src/main/java/com/example/majorLink/controller/LectureController.java
  majorLink/src/main/java/com/example/majorLink/controller/ReviewController.java
  majorLink/src/main/java/com/example/majorLink/domain/Lecture.java
  majorLink/src/main/java/com/example/majorLink/dto/request/LectureRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/LectureResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/ReviewResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/CategoryRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/LectureRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/LikedRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/TuteeLectureRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/TutorLectureRepository.java
  majorLink/src/main/java/com/example/majorLink/service/LectureService.java
  majorLink/src/main/java/com/example/majorLink/service/LectureServiceImpl.java
Labels: 🐛 bug, ✨ feature

#51 🚑 [HOTFIX] 첫 소셜 로그인 시도 시 providerId 반환 오류
  .idea/modules.xml
  majorLink/src/main/java/com/example/majorLink/global/oauth2/OAuthAttributes.java
Labels: 🚑 Hotfix

#52 ✨ [FEAT] 알림 기능 #38
  majorLink/src/main/java/com/example/majorLink/controller/NotificationController.java
  majorLink/src/main/java/com/example/majorLink/domain/Lecture.java
  majorLink/src/main/java/com/example/majorLink/domain/Notification.java
  majorLink/src/main/java/com/example/majorLink/domain/NotificationContent.java
  majorLink/src/main/java/com/example/majorLink/domain/RelatedUrl.java
  majorLink/src/main/java/com/example/majorLink/domain/User.java
  majorLink/src/main/java/com/example/majorLink/domain/enums/NotificationType.java
  majorLink/src/main/java/com/example/majorLink/dto/response/NotificationResponse.java
  majorLink/src/main/java/com/example/majorLink/repository/EmitterRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/EmitterRepositoryImpl.java
  majorLink/src/main/java/com/example/majorLink/repository/NotificationRepository.java
  majorLink/src/main/java/com/example/majorLink/service/LectureServiceImpl.java
  majorLink/src/main/java/com/example/majorLink/service/NotificationService.java
  majorLink/src/main/java/com/example/majorLink/service/NotificationServiceImpl.java
Labels: ✨ feature

#53 화상채팅 기능 구현(WebRTC + websocket)
  majorLink/build.gradle
  majorLink/src/main/java/com/example/majorLink/global/config/WebConfig.java
  majorLink/src/main/java/com/example/majorLink/global/config/WebSocketLiveConfig.java
  majorLink/src/main/java/com/example/majorLink/handler/VideoChatWebSocketHandler.java
Labels: ✨ feature

#54 🚑 [HOTFIX] CORS 에러로 인해 권한 수정
  majorLink/src/main/java/com/example/majorLink/global/config/WebConfig.java
Labels: 🚑 Hotfix

#56 🚑 [HOTFIX] CORS 에러로 인해 권한 수정2
  .idea/modules.xml
  majorLink/src/main/java/com/example/majorLink/global/config/SecurityConfig.java
  majorLink/src/main/java/com/example/majorLink/global/config/WebConfig.java
Labels: 🚑 Hotfix

#57 🚑 [HOTFIX] CORS 에러로 인해 권한 수정3
  majorLink/src/main/java/com/example/majorLink/global/config/SecurityConfig.java
  majorLink/src/main/java/com/example/majorLink/global/config/WebConfig.java
Labels: 🚑 Hotfix

#60 🚑 [HOTFIX] CORS 에러로 인해 권한 수정5
  majorLink/src/main/java/com/example/majorLink/global/config/SecurityConfig.java
Labels: 🚑 Hotfix

#61 🔥 [DELETE] CORS 처리 확인을 위한 임시 삭제
  majorLink/src/main/java/com/example/majorLink/global/config/SecurityConfig.java
Labels: test

#69 🚑 [HOTFIX] CORS 에러로 인한 임시 수정
  majorLink/src/main/java/com/example/majorLink/global/config/SecurityConfig.java
Labels: 🚑 Hotfix

#71 ♻️ [REFACTOR] 강의 이미지 추가 및 강의 평점 조회
  majorLink/src/main/java/com/example/majorLink/controller/LectureController.java
  majorLink/src/main/java/com/example/majorLink/controller/ReviewController.java
  majorLink/src/main/java/com/example/majorLink/domain/Lecture.java
  majorLink/src/main/java/com/example/majorLink/domain/Review.java
  majorLink/src/main/java/com/example/majorLink/dto/request/LectureRequestDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/LectureResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/ReviewResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/ReviewRepository.java
  majorLink/src/main/java/com/example/majorLink/service/LectureServiceImpl.java
Labels: ♻️ refactor

#81 Bug#80
  majorLink/src/main/java/com/example/majorLink/controller/LectureController.java
  majorLink/src/main/java/com/example/majorLink/controller/ReviewController.java
  majorLink/src/main/java/com/example/majorLink/repository/ReviewRepository.java
  majorLink/src/main/java/com/example/majorLink/service/ReviewService/ReviewService.java
  majorLink/src/main/java/com/example/majorLink/service/ReviewService/ReviewServiceImpl.java
Labels: 🐛 bug

#85 ♻️ [REFACTOR] 토큰 검증을 통해 userId를 받아올 수 있도록 수정
  majorLink/src/main/java/com/example/majorLink/controller/NotificationController.java
  majorLink/src/main/java/com/example/majorLink/service/NotificationService.java
  majorLink/src/main/java/com/example/majorLink/service/NotificationServiceImpl.java
Labels: ♻️ refactor

#86 🚑 [HOTFIX] HTTP2 사용을 위한 yml 수정
  majorLink/src/main/resources/application.yml
Labels: 🚑 Hotfix

#87 ♻️ [REFACTOR] 알림 전송 시 receiver가 아닌 sender에게 알림이 가는 오류 해결
  majorLink/src/main/java/com/example/majorLink/controller/NotificationController.java
  majorLink/src/main/java/com/example/majorLink/service/NotificationServiceImpl.java
  majorLink/src/main/resources/static/index.html
Labels: ♻️ refactor

#88 ♻️ [FEAT] 응답 수정
  majorLink/src/main/java/com/example/majorLink/controller/PaymentController.java
  majorLink/src/main/java/com/example/majorLink/dto/response/ProductOrderResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/dto/response/ReviewResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/service/PaymentService/PaymentServiceImpl.java
Labels: ♻️ refactor

#96 ♻️ [REFACTOR] sender와 receiver에 동일한 user 정보가 저장되던 오류 해결
  majorLink/src/main/java/com/example/majorLink/domain/User.java
  majorLink/src/main/java/com/example/majorLink/service/NotificationServiceImpl.java
  majorLink/src/main/resources/application.yml
Labels: ♻️ refactor

#98 ♻️ Feat: 카테고리 조회 api 리팩토링
  majorLink/src/main/java/com/example/majorLink/controller/LectureController.java
  majorLink/src/main/java/com/example/majorLink/controller/PaymentController.java
  majorLink/src/main/java/com/example/majorLink/dto/response/LectureResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/CategoryRepository.java
  majorLink/src/main/java/com/example/majorLink/service/LectureService.java
  majorLink/src/main/java/com/example/majorLink/service/LectureServiceImpl.java
Labels: ♻️ refactor

#110 test api 추가
  majorLink/src/main/java/com/example/majorLink/controller/ChatController.java
Labels: test

#103 ♻️ [REFACTOR] TutorLecture 삭제
  majorLink/src/main/java/com/example/majorLink/controller/LectureController.java
  majorLink/src/main/java/com/example/majorLink/domain/User.java
  majorLink/src/main/java/com/example/majorLink/domain/mapping/TutorLecture.java
  majorLink/src/main/java/com/example/majorLink/dto/response/LectureResponseDTO.java
  majorLink/src/main/java/com/example/majorLink/repository/LectureRepository.java
  majorLink/src/main/java/com/example/majorLink/repository/TutorLectureRepository.java
  majorLink/src/main/java/com/example/majorLink/service/LectureService.java
  majorLink/src/main/java/com/example/majorLink/service/LectureServiceImpl.java
  majorLink/src/main/java/com/example/majorLink/service/PaymentService/PaymentServiceImpl.java
Labels: ♻️ refactor

#101 :sparkles: Feat: 결제 시 포인트 증가
  majorLink/src/main/java/com/example/majorLink/domain/User.java
  majorLink/src/main/java/com/example/majorLink/service/PaymentService/PaymentServiceImpl.java
Labels: ✨ feature
